language: node_js
env:
  global:
    - CXX=g++-4.8
    - SKIP_REAL_S3_TESTS=yes
node_js:
- '10'
- '11'
addons:
  apt:
      sources:
        - ubuntu-toolchain-r-test
      packages:
        - g++-4.8
  sudo: false
  hosts:
    - test-bucket.localhost
